# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Server
version:      0.97
version_from: lib/Net/Server.pm
installdirs:  site
requires:
    IO::Socket:                    0
    POSIX:                         0
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
